export const weddingConfig = {
  heroBannerImage: "/images/banner2.webp",
  musicUrl: "/music/song.mp3",
  video: {
    opening: "/video/intro.mp4",
  },
  venueLocation: {
    name: "The Royal Palace Gardens",
    address: "123 Palace Road, Jaipur, Rajasthan",
    query: "The Royal Palace Gardens, Jaipur, Rajasthan",
    embedUrl: "https://www.google.com/maps?q=The%20Royal%20Palace%20Gardens%2C%20Jaipur%2C%20Rajasthan&output=embed",
    directionUrl: "https://www.google.com/maps/dir/?api=1&destination=The%20Royal%20Palace%20Gardens%2C%20123%20Palace%20Road%2C%20Jaipur%2C%20Rajasthan",
  },
  bride: {
    name: "Ananya",
    fullName: "Ananya Sharma",
    parents: "Mr. Raj & Mrs. Meera Sharma",
  },
  groom: {
    name: "Vikram",
    fullName: "Vikram Singh",
    parents: "Mr. Anil & Mrs. Sunita Singh",
  },
  weddingDate: "2026-11-20T17:00:00",
  hashtag: "#AnanyaGotVikramed",
  quote: "Two souls with but a single thought, two hearts that beat as one.",
  theme: {
    colors: {
      primary: "#800000",
      secondary: "#F5F5DC",
      accent: "#D4AF37",
      background: "#FFFAF0",
      text: "#333333",
    },
  },
  story: [
    {
      title: "How We Met",
      date: "August 2022",
      description: "A chance encounter at a mutual friend's art gallery opening. A conversation about a painting led to a coffee date the next day.",
      image: "/images/s1.webp",
    },
    {
      title: "The First Date",
      date: "September 2022",
      description: "A beautiful evening by the lake, talking for hours until the stars came out. We knew there was something special.",
      image: "/images/s2.webp",
    },
    {
      title: "The Proposal",
      date: "December 2025",
      description: "A surprise trip to Udaipur. Overlooking the Pichola lake at sunset, Vikram went down on one knee.",
      image: "/images/s3.webp",
    },
  ],
  events: [
    {
      id: "haldi",
      title: "Haldi Ceremony",
      date: "2026-11-18T10:00:00",
      venue: "The Royal Palace Gardens",
      address: "123 Palace Road, Jaipur, Rajasthan",
      dressCode: "Yellow / White Traditional",
      mapUrl: "https://www.google.com/maps/dir/?api=1&destination=The%20Royal%20Palace%20Gardens%2C%20Jaipur%2C%20Rajasthan",
      description: "Join us for a morning of vibrant colors, traditional music, and the beautiful Haldi ritual to bless the couple.",
      image: "/images/haldi.webp",
    },
    {
      id: "Mehndi",
      title: "Mehndi",
      date: "2026-11-19T19:00:00",
      venue: "The Grand Durbar Hall",
      address: "123 Palace Road, Jaipur, Rajasthan",
      dressCode: "Glamorous / Indo-Western",
      mapUrl: "https://www.google.com/maps/dir/?api=1&destination=The%20Grand%20Durbar%20Hall%2C%20Jaipur%2C%20Rajasthan",
      description: "An evening of dance, music, and celebration. Bring your dancing shoes!",
      image: "/images/mehndi.webp",
    },
    {
      id: "ring",
      title: "Ring Ceremony",
      date: "2026-11-17T19:00:00",
      venue: "The Royal Ballroom",
      address: "123 Palace Road, Jaipur, Rajasthan",
      dressCode: "Elegant Traditional",
      mapUrl: "https://www.google.com/maps/dir/?api=1&destination=The%20Royal%20Ballroom%2C%20Jaipur%2C%20Rajasthan",
      description: "Join us as we exchange rings and begin our journey together with our loved ones.",
      image: "/images/ring.webp",
    },
    {
      id: "wedding",
      title: "The Wedding",
      date: "2026-11-20T17:00:00",
      venue: "The Lakefront Pavilion",
      address: "123 Palace Road, Jaipur, Rajasthan",
      dressCode: "Traditional / Formals",
      mapUrl: "https://www.google.com/maps/dir/?api=1&destination=The%20Lakefront%20Pavilion%2C%20Jaipur%2C%20Rajasthan",
      description: "The moment we tie the knot. Sunset pheras followed by a grand reception dinner.",
      image: "/images/wedding.webp",
    },
  ],
  gallery: [
    "/images/g1.webp",
    "/images/g2.webp",
    "/images/g3.webp",
    "/images/g4.webp",
    "/images/g5.webp",
    "/images/g6.webp",
  ],
  family: {
    bride: [
      { name: "Rahul Sharma", relation: "Brother", image: "/images/family_rahul.jpg" },
      { name: "Priya Sharma", relation: "Sister", image: "/images/family_priya.jpg" },
    ],
    groom: [
      { name: "Aditya Singh", relation: "Brother", image: "/images/family_aditya.jpg" },
      { name: "Neha Singh", relation: "Sister", image: "/images/family_neha.jpg" },
    ],
  },
  scratchCard: {
    title: "Scratch to Reveal the Wedding Date",
    dateText: "November 20, 2026 • Jaipur, Rajasthan",
    blessingText: "You are cordially invited to witness our royal union!",
    revealedTitle: "Date & Details Revealed!",
  },
  travel: {
    airport: "Jaipur International Airport (JAI)\nApprox. 30 minutes drive from the venue.",
    railway: "Jaipur Junction (JP)\nApprox. 20 minutes drive from the venue.",
    hotelsNotice: "We have arranged block bookings at nearby properties. Please mention '#AnanyaGotVikramed' while booking to avail special rates.",
  },
  contact: {
    email: "wedding@ananyavikram.com",
    phone: "+91 98765 43210",
  },
};
